// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.OpenIddict;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.OpenIddict;

public interface IOpenIddictScopeAppService : IApplicationService
{
    Task<OpenIddictScopeDto> GetAsync(Guid id);

    Task<OpenIddictScopeDto> FindByNameAsync(string name);

    Task<PagedResultDto<OpenIddictScopeDto>> GetPagedListAsync(PagedAndSortedResultRequestDto input);

    Task<List<OpenIddictScopeDto>> GetListAsync();

    Task<OpenIddictScopeDto> CreateAsync(CreateOpenIddictScopeDto input);

    Task<OpenIddictScopeDto> UpdateAsync(Guid id, UpdateOpenIddictScopeDto input);

    Task DeleteAsync(Guid id);
}
