// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using SharpAbp.Abp.Identity;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentitySecurityLogAppService), typeof(IdentitySecurityLogClientProxy))]
public partial class IdentitySecurityLogClientProxy : ClientProxyBase<IIdentitySecurityLogAppService>, IIdentitySecurityLogAppService
{
    public virtual async Task<IdentitySecurityLogDto> GetAsync(Guid id)
    {
        return await RequestAsync<IdentitySecurityLogDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<IdentitySecurityLogDto>> GetPagedListAsync(IdentitySecurityLogPagedRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IdentitySecurityLogDto>>(nameof(GetPagedListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IdentitySecurityLogPagedRequestDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
