// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.AuditLogging;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.AuditLogging;

public class AuditLogDto : ExtensibleEntityDto<Guid>
{
    public string ApplicationName { get; set; }

    public Guid? UserId { get; set; }

    public string UserName { get; set; }

    public Guid? TenantId { get; set; }

    public string TenantName { get; set; }

    public Guid? ImpersonatorUserId { get; set; }

    public Guid? ImpersonatorTenantId { get; set; }

    public string ImpersonatorTenantName { get; set; }

    public DateTime ExecutionTime { get; set; }

    public int ExecutionDuration { get; set; }

    public string ClientIpAddress { get; set; }

    public string ClientName { get; set; }

    public string ClientId { get; set; }

    public string CorrelationId { get; set; }

    public string BrowserInfo { get; set; }

    public string HttpMethod { get; set; }

    public string Url { get; set; }

    public string Exceptions { get; set; }

    public string Comments { get; set; }

    public int? HttpStatusCode { get; set; }

    public EntityChangeDto[] EntityChanges { get; set; }

    public AuditLogActionDto[] Actions { get; set; }
}
