// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.AuditLogging;
using System;
using System.Collections.Generic;
using System.Net;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.AuditLogging;

public class AuditLogPagedRequestDto : PagedAndSortedResultRequestDto
{
    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string HttpMethod { get; set; }

    public string Url { get; set; }

    public Guid? UserId { get; set; }

    public string UserName { get; set; }

    public string ApplicationName { get; set; }

    public string ClientIpAddress { get; set; }

    public string CorrelationId { get; set; }

    public int? MaxExecutionDuration { get; set; }

    public int? MinExecutionDuration { get; set; }

    public bool? HasException { get; set; }

    public HttpStatusCode? HttpStatusCode { get; set; }
}
