// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.AuditLogging;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Auditing;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.AuditLogging;

public class EntityChangePagedRequestDto : PagedAndSortedResultRequestDto
{
    public Guid? AuditLogId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public EntityChangeType? ChangeType { get; set; }

    public string EntityId { get; set; }

    public string EntityTypeFullName { get; set; }
}
