// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.AuditLogging;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Auditing;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.AuditLogging;

public class EntityChangeDto : EntityDto<Guid>
{
    public Guid AuditLogId { get; set; }

    public Guid? TenantId { get; set; }

    public DateTime ChangeTime { get; set; }

    public EntityChangeType ChangeType { get; set; }

    public Guid? EntityTenantId { get; set; }

    public string EntityId { get; set; }

    public string EntityTypeFullName { get; set; }

    public EntityPropertyChangeDto[] PropertyChanges { get; set; }

    public Dictionary<string, object> ExtraProperties { get; set; }
}
