// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.AuditLogging;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.AuditLogging;

public class EntityPropertyChangeDto : EntityDto<Guid>
{
    public Guid? TenantId { get; set; }

    public Guid EntityChangeId { get; set; }

    public string NewValue { get; set; }

    public string OriginalValue { get; set; }

    public string PropertyName { get; set; }

    public string PropertyTypeFullName { get; set; }
}
