// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.AuditLogging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.AuditLogging;

public interface IAuditLogAppService : IApplicationService
{
    Task<AuditLogDto> GetAsync(Guid id);

    Task<PagedResultDto<AuditLogDto>> GetPagedListAsync(AuditLogPagedRequestDto input);

    Task<PagedResultDto<EntityChangeDto>> GetEntityChangePagedListAsync(EntityChangePagedRequestDto input);

    Task<EntityChangeWithUsernameDto> GetEntityChangeWithUsernameAsync(Guid entityChangeId);

    Task<List<EntityChangeWithUsernameDto>> GetEntityChangesWithUsernameAsync(string entityId, string entityTypeFullName);

    Task DeleteAsync(Guid id);
}
