// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.MinId;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.MinId;

public interface IMinIdTokenAppService : IApplicationService
{
    Task<MinIdTokenDto> GetAsync(Guid id);

    Task<MinIdTokenDto> FindByTokenAsync(string bizType, string token);

    Task<PagedResultDto<MinIdTokenDto>> GetPagedListAsync(MinIdTokenPagedRequestDto input);

    Task<MinIdTokenDto> CreateAsync(CreateMinIdTokenDto input);

    Task<MinIdTokenDto> UpdateAsync(Guid id, UpdateMinIdTokenDto input);

    Task DeleteAsync(Guid id);
}
