// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.MinId;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.MinId;

public interface IMinIdInfoAppService : IApplicationService
{
    Task<MinIdInfoDto> GetAsync(Guid id);

    Task<MinIdInfoDto> FindByBizTypeAsync(string bizType);

    Task<PagedResultDto<MinIdInfoDto>> GetPagedListAsync(MinIdInfoPagedRequestDto input);

    Task<List<MinIdInfoDto>> GetListAsync(string sorting, string bizType);

    Task<MinIdInfoDto> CreateAsync(CreateMinIdInfoDto input);

    Task<MinIdInfoDto> UpdateAsync(Guid id, UpdateMinIdInfoDto input);

    Task DeleteAsync(Guid id);
}
