// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.MinId;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.MinId;

public class MinIdTokenPagedRequestDto : PagedAndSortedResultRequestDto
{
    public string BizType { get; set; }

    public string Token { get; set; }
}
