// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.MinId;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.MinId;

public class MinIdInfoDto : AuditedEntityDto<Guid>
{
    public string BizType { get; set; }

    public long MaxId { get; set; }

    public int Step { get; set; }

    public int Delta { get; set; }

    public int Remainder { get; set; }
}
