// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.MapTenancyManagement;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;
using Volo.Abp.TenantManagement;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.MapTenancyManagement;

public class CreateHybridMapTenantDto : TenantCreateOrUpdateDtoBase
{
    public string AdminEmailAddress { get; set; }

    public string AdminPassword { get; set; }

    public string Code { get; set; }

    public string MapCode { get; set; }
}
