// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.MapTenancyManagement;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.MapTenancyManagement;

public class HybridMapTenantDto : ExtensibleEntityDto<Guid>
{
    public string Name { get; set; }

    public string ConcurrencyStamp { get; set; }

    public Guid? MapTenantId { get; set; }

    public string Code { get; set; }

    public string MapCode { get; set; }
}
