// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.MapTenancyManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.MapTenancyManagement;

public interface IHybridMapTenantAppService : IApplicationService
{
    Task<HybridMapTenantDto> GetAsync(Guid id);

    Task<List<HybridMapTenantDto>> GetAllAsync();

    Task<PagedResultDto<HybridMapTenantDto>> GetListAsync(HybridMapTenantPagedRequestDto input);

    Task<PagedResultDto<HybridMapTenantDto>> SearchAsync(HybridMapTenantPagedRequestDto input);

    Task<HybridMapTenantDto> CurrentAsync();

    Task<HybridMapTenantDto> CreateAsync(CreateHybridMapTenantDto input);

    Task<HybridMapTenantDto> UpdateAsync(Guid id, UpdateHybridMapTenantDto input);

    Task DeleteAsync(Guid id);

    Task<string> GetDefaultConnectionStringAsync(Guid id);

    Task UpdateDefaultConnectionStringAsync(Guid id, string defaultConnectionString);

    Task DeleteDefaultConnectionStringAsync(Guid id);
}
