// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.MapTenancyManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.MapTenancyManagement;

public interface IMapTenantAppService : IApplicationService
{
    Task<MapTenantDto> GetAsync(Guid id);

    Task<MapTenantDto> FindByCodeAsync(string code);

    Task<MapTenantDto> FindByMapCodeAsync(string mapCode);

    Task<MapTenantDto> FindByTenantIdAsync(Guid tenantId);

    Task<PagedResultDto<MapTenantDto>> GetPagedListAsync(MapTenantPagedRequestDto input);

    Task<MapTenantDto> CreateAsync(CreateMapTenantDto input);

    Task<MapTenantDto> UpdateAsync(Guid id, UpdateMapTenantDto input);

    Task DeleteAsync(Guid id);
}
