// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using SharpAbp.Abp.IdentityServer.IdentityResources;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.IdentityServer.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityResourceAppService), typeof(IdentityResourceClientProxy))]
public partial class IdentityResourceClientProxy : ClientProxyBase<IIdentityResourceAppService>, IIdentityResourceAppService
{
    public virtual async Task<IdentityResourceDto> GetAsync(Guid id)
    {
        return await RequestAsync<IdentityResourceDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IdentityResourceDto> FindByNameAsync(string name)
    {
        return await RequestAsync<IdentityResourceDto>(nameof(FindByNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), name }
        });
    }

    public virtual async Task<PagedResultDto<IdentityResourceDto>> GetPagedListAsync(IdentityResourcePagedRequestDto input)
    {
        return await RequestAsync<PagedResultDto<IdentityResourceDto>>(nameof(GetPagedListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(IdentityResourcePagedRequestDto), input }
        });
    }

    public virtual async Task<List<IdentityResourceDto>> GetListByScopeNameAsync(String[] scopeNames)
    {
        return await RequestAsync<List<IdentityResourceDto>>(nameof(GetListByScopeNameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(String[]), scopeNames }
        });
    }

    public virtual async Task<List<IdentityResourceDto>> GetAllAsync()
    {
        return await RequestAsync<List<IdentityResourceDto>>(nameof(GetAllAsync));
    }

    public virtual async Task<Guid> CreateAsync(CreateIdentityResourceDto input)
    {
        return await RequestAsync<Guid>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateIdentityResourceDto), input }
        });
    }

    public virtual async Task UpdateAsync(Guid id, UpdateIdentityResourceDto input)
    {
        await RequestAsync(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateIdentityResourceDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
