// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.Identity;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Identity;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity;

public class CreateIdentityClaimTypeDto
{
    public string Name { get; set; }

    public bool Required { get; set; }

    public bool IsStatic { get; set; }

    public string Regex { get; set; }

    public string RegexDescription { get; set; }

    public string Description { get; set; }

    public IdentityClaimValueType ValueType { get; set; }
}
