// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.Identity;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity;

public class IdentitySettingsDto
{
    public IdentityLockoutSettingsDto Lockout { get; set; }

    public IdentityPasswordSettingsDto Password { get; set; }

    public IdentitySignInSettingsDto SignIn { get; set; }

    public IdentityUserSettingsDto User { get; set; }
}
