// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.Identity;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;
using Volo.Abp.Identity;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityUserAppService), typeof(IdentityUserClientProxy))]
public partial class IdentityUserClientProxy : ClientProxyBase<IIdentityUserAppService>, IIdentityUserAppService
{
    public virtual async Task<IdentityUserDto> GetAsync(Guid id)
    {
        return await RequestAsync<IdentityUserDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<IdentityUserDto> FindByEmailAsync(string email)
    {
        return await RequestAsync<IdentityUserDto>(nameof(FindByEmailAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), email }
        });
    }

    public virtual async Task<PagedResultDto<IdentityUserDto>> GetListAsync(GetIdentityUsersInput input)
    {
        return await RequestAsync<PagedResultDto<IdentityUserDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetIdentityUsersInput), input }
        });
    }

    public virtual async Task<IdentityUserDto> FindByUsernameAsync(string userName)
    {
        return await RequestAsync<IdentityUserDto>(nameof(FindByUsernameAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), userName }
        });
    }

    public virtual async Task<IdentityUserDto> CreateAsync(NewIdentityUserCreateDto input)
    {
        return await RequestAsync<IdentityUserDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NewIdentityUserCreateDto), input }
        });
    }

    public virtual async Task<IdentityUserDto> UpdateAsync(Guid id, NewIdentityUserUpdateDto input)
    {
        return await RequestAsync<IdentityUserDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(NewIdentityUserUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<IdentityClaimTypeDto>> GetAllClaimTypesAsync()
    {
        return await RequestAsync<List<IdentityClaimTypeDto>>(nameof(GetAllClaimTypesAsync));
    }

    public virtual async Task<ListResultDto<IdentityRoleDto>> GetRolesAsync(Guid id)
    {
        return await RequestAsync<ListResultDto<IdentityRoleDto>>(nameof(GetRolesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<IdentityRoleDto>> GetAssignableRolesAsync()
    {
        return await RequestAsync<ListResultDto<IdentityRoleDto>>(nameof(GetAssignableRolesAsync));
    }

    public virtual async Task UpdateRolesAsync(Guid id, IdentityUserUpdateRolesDto input)
    {
        await RequestAsync(nameof(UpdateRolesAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(IdentityUserUpdateRolesDto), input }
        });
    }

    public virtual async Task<List<IdentityUserClaimDto>> GetClaimsAsync(Guid id)
    {
        return await RequestAsync<List<IdentityUserClaimDto>>(nameof(GetClaimsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task UpdateClaimsAsync(Guid id, List<CreateOrUpdateIdentityUserClaimDto> identityUserClaims)
    {
        await RequestAsync(nameof(UpdateClaimsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(List<CreateOrUpdateIdentityUserClaimDto>), identityUserClaims }
        });
    }

    public virtual async Task<List<OrganizationUnitDto>> GetOrganizationUnitsAsync(Guid id)
    {
        return await RequestAsync<List<OrganizationUnitDto>>(nameof(GetOrganizationUnitsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<ListResultDto<OrganizationUnitDto>> GetAvailableOrganizationUnitsAsync()
    {
        return await RequestAsync<ListResultDto<OrganizationUnitDto>>(nameof(GetAvailableOrganizationUnitsAsync));
    }

    public virtual async Task LockAsync(Guid id, int seconds)
    {
        await RequestAsync(nameof(LockAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(int), seconds }
        });
    }

    public virtual async Task UnLockAsync(Guid id)
    {
        await RequestAsync(nameof(UnLockAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task SetPasswordAsync(Guid id, SetPasswordDto input)
    {
        await RequestAsync(nameof(SetPasswordAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(SetPasswordDto), input }
        });
    }

    public virtual async Task<bool> TwoFactorEnableAsync(Guid id)
    {
        return await RequestAsync<bool>(nameof(TwoFactorEnableAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task SetTwoFactorAsync(Guid id, bool enabled)
    {
        await RequestAsync(nameof(SetTwoFactorAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(bool), enabled }
        });
    }
}
