// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.Identity;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity;

public interface IIdentityClaimTypeAppService : IApplicationService
{
    Task<IdentityClaimTypeDto> GetAsync(Guid id);

    Task<bool> AnyAsync(string name, Guid? ignoredId);

    Task<PagedResultDto<IdentityClaimTypeDto>> GetPagedListAsync(IdentityClaimTypePagedRequestDto input);

    Task<Guid> CreateAsync(CreateIdentityClaimTypeDto input);

    Task UpdateAsync(Guid id, UpdateIdentityClaimTypeDto input);

    Task DeleteAsync(Guid id);
}
