// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.Identity;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Identity;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity;

public class NewIdentityUserCreateDto : IdentityUserCreateOrUpdateDtoBase
{
    public string Password { get; set; }

    public Guid[] OrganizationUnitIds { get; set; }
}
