// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.Identity;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.Identity;

public class OrganizationUnitDto : ExtensibleFullAuditedEntityDto<Guid>
{
    public Guid? TenantId { get; set; }

    public Guid? ParentId { get; set; }

    public string Code { get; set; }

    public string DisplayName { get; set; }

    public OrganizationUnitRoleDto[] Roles { get; set; }
}
