// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.FileStoringManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.FileStoringManagement;

public interface IContainerAppService : IApplicationService
{
    Task<ContainerDto> GetAsync(Guid id);

    Task<ContainerDto> FindByNameAsync(string name);

    Task<PagedResultDto<ContainerDto>> GetPagedListAsync(FileStoringContainerPagedRequestDto input);

    Task<List<ContainerDto>> GetAllAsync();

    Task<ContainerDto> CreateAsync(CreateContainerDto input);

    Task<ContainerDto> UpdateAsync(Guid id, UpdateContainerDto input);

    Task DeleteAsync(Guid id);
}
