// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.FileStoringManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.FileStoringManagement;

public interface IFileProviderAppService : IApplicationService
{
    Task<List<ProviderDto>> GetProvidersAsync();

    Task<bool> HasProviderAsync(string provider);

    Task<ProviderOptionsDto> GetOptionsAsync(string provider);
}
