// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.FileStoringManagement;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.FileStoringManagement;

public class ProviderOptionsDto
{
    public string Provider { get; set; }

    public ProviderValueDto[] Values { get; set; }
}
