// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.FileStoringManagement;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.FileStoringManagement;

public class ProviderValueDto
{
    public string Name { get; set; }

    public string LocalizationValue { get; set; }

    public string Type { get; set; }

    public string Eg { get; set; }

    public string Note { get; set; }
}
