using System;

namespace SharpAbp.Abp.FileStoring
{
    /// <summary>
    /// Top-level switch that determines the overall path building mode.
    /// <list type="bullet">
    /// <item><term>TenantBased</term><description>
    ///   Default. Produces structured paths such as <c>host/{fileId}</c> or
    ///   <c>tenants/{id}/{fileId}</c>.  Fine-grained control (prefix, custom tenant
    ///   identifier, per-operation overrides) is available through
    ///   <see cref="AbpFileStoringAbstractionsOptions.FilePathBuilder"/>.
    /// </description></item>
    /// <item><term>DirectFileId</term><description>
    ///   Bypasses all structural logic and uses the raw <c>fileId</c> as the storage key.
    ///   <see cref="AbpFileStoringAbstractionsOptions.FilePathBuilder"/> prefix is still applied
    ///   when set, but tenant/host segments are omitted entirely.
    /// </description></item>
    /// </list>
    /// </summary>
    public enum FilePathGenerationStrategy
    {
        /// <summary>
        /// Structured path with optional prefix and tenant segment (default).
        /// </summary>
        TenantBased,

        /// <summary>
        /// Use FileId directly as the storage key, skipping tenant/host segments.
        /// </summary>
        DirectFileId
    }

    public class AbpFileStoringAbstractionsOptions
    {
        public int DefaultClientMaximumRetained { get; set; } = Environment.ProcessorCount * 2;

        /// <summary>
        /// Determines how file paths are generated by FileNameCalculators.
        /// Default: TenantBased (maintains backward compatibility).
        /// </summary>
        public FilePathGenerationStrategy FilePathStrategy { get; set; } = FilePathGenerationStrategy.TenantBased;

        /// <summary>
        /// Configures path building behaviour: prefix, tenant identifier factory, etc.
        /// Per-operation overrides can be supplied via <see cref="IFilePathContextAccessor"/>.
        /// </summary>
        public FilePathBuilderOptions FilePathBuilder { get; set; } = new FilePathBuilderOptions();

        public FileProviderConfigurations Providers { get; }

        public AbpFileStoringAbstractionsOptions()
        {
            Providers = new FileProviderConfigurations();
        }
    }
}
