using System;

namespace SharpAbp.Abp.FileStoring
{
    /// <summary>
    /// Defines how file paths should be generated by FileNameCalculators.
    /// </summary>
    public enum FilePathGenerationStrategy
    {
        /// <summary>
        /// Use tenant-based path structure: "host/{fileId}" for host, "tenants/{tenantId}/{fileId}" for tenants.
        /// This is the default behavior.
        /// </summary>
        TenantBased,

        /// <summary>
        /// Use FileId directly as the object key without any tenant path prefix.
        /// </summary>
        DirectFileId
    }

    public class AbpFileStoringAbstractionsOptions
    {
        public int DefaultClientMaximumRetained { get; set; } = Environment.ProcessorCount * 2;

        /// <summary>
        /// Determines how file paths are generated by FileNameCalculators.
        /// Default: TenantBased (maintains backward compatibility).
        /// </summary>
        public FilePathGenerationStrategy FilePathStrategy { get; set; } = FilePathGenerationStrategy.TenantBased;

        public FileProviderConfigurations Providers { get; }

        public AbpFileStoringAbstractionsOptions()
        {
            Providers = new FileProviderConfigurations();
        }
    }
}
