// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.DbConnectionsManagement;
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.DbConnectionsManagement;

public class DatabaseConnectionInfoPagedRequestDto : PagedAndSortedResultRequestDto
{
    public string Name { get; set; }

    public string DatabaseProvider { get; set; }
}
