// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.DbConnectionsManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.DbConnectionsManagement;

public interface IDatabaseConnectionInfoAppService : IApplicationService
{
    Task<DatabaseConnectionInfoDto> GetAsync(Guid id);

    Task<DatabaseConnectionInfoDto> FindByNameAsync(string name);

    Task<List<DatabaseConnectionInfoDto>> GetListAsync(string sorting, string name, string databaseProvider);

    Task<PagedResultDto<DatabaseConnectionInfoDto>> GetPagedListAsync(DatabaseConnectionInfoPagedRequestDto input);

    Task<DatabaseConnectionInfoDto> CreateAsync(CreateDatabaseConnectionInfoDto input);

    Task<DatabaseConnectionInfoDto> UpdateAsync(Guid id, UpdateDatabaseConnectionInfoDto input);

    Task DeleteAsync(Guid id);
}
