// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using SharpAbp.Abp.DbConnectionsManagement;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace SharpAbp.Abp.DbConnectionsManagement;

public interface IDatabaseProviderAppService : IApplicationService
{
    Task<List<String>> GetAllAsync();
}
